import type {Metadata} from "next"
import {Inter} from "next/font/google"
import {Toaster} from "react-hot-toast"
import "./globals.css"

const inter = Inter({
    subsets: ["latin"],
    variable: "--font-inter",
})

export const metadata: Metadata = {
    title: "Expense tracker",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en'>
            <body
                className={`${inter.className} antialiased w-[90%] max-w-[1200px] m-auto`}
            >
                {children}
                <Toaster />
            </body>
        </html>
    )
}
